### ISSUE TITLE
Can't save the model

### ISSUE THREAD

**Issue by khronosplus** [hiteshvaidya/Model-Compression#2]
when I ran mnist_cnn_*.py, ValueError: Parent directory of trained_weights.ckpt doesn't exist, can't save.

**Comment by hiteshvaidya** [comment]
Hi @khronosplus,
My apologies for replying so late. I suggest you please contact the following author,
Author: Aymeric Damien
Project: https://github.com/aymericdamien/TensorFlow-Examples/
Let me know if the problem gets solved with his help.

**Comment by AHEADer** [comment]
you can refer to this: [tensorflow/tensorflow#11157](https://github.com/tensorflow/tensorflow/issues/11157), it's still a problem. There's no way to use pickle.dump

**Comment by AHEADer** [comment]
@khronosplus , you can fix it by using an absolute path for the file instead of just the bare filename.
